import { Beacon } from "../../src/entities/Beacon";
import { Registration } from "../../src/entities/Registration";
import { beaconToRegistration } from "../../src/lib/beaconToRegistration";
import { beaconFixtures } from "../fixtures/beacons.fixture";

describe("beaconToRegistration", () => {
  it("maps a Beacon to a Registration", () => {
    const beacon: Beacon = beaconFixtures[0];

    const registration: Registration = beaconToRegistration(beacon);

    expect(registration).toStrictEqual(expectedRegistration);
  });
});

const expectedRegistration: Registration = {
  id: "f48e8212-2e10-4154-95c7-bdfd061bcfd2",
  manufacturer: "Ocean Signal",
  model: "Excelsior",
  hexId: "1D0EA08C52FFBFF",
  referenceNumber: "A1B2C3B4",
  accountHolderId: "b32deeb3-031f-4be7-ab16-681a8cac7ddd",
  registeredDate: "2018-06-08",
  manufacturerSerialNumber: "1407312904",
  chkCode: "456QWE",
  batteryExpiryDate: "2020-02-01",
  batteryExpiryDateMonth: "02",
  batteryExpiryDateYear: "2020",
  lastServicedDate: "2020-02-01",
  lastServicedDateMonth: "02",
  lastServicedDateYear: "2020",
  ownerFullName: "Steve Stevington",
  ownerEmail: "steve@beaconowner.com",
  ownerTelephoneNumber: "07872536271",
  ownerAlternativeTelephoneNumber: null,
  ownerAddressLine1: "1 Beacon Square",
  ownerAddressLine2: "",
  ownerTownOrCity: "Beaconsfield",
  ownerCounty: "Yorkshire",
  ownerPostcode: "BS8 7NW",
  emergencyContact1FullName: "Lady Hamilton",
  emergencyContact1TelephoneNumber: "02392 856621",
  emergencyContact1AlternativeTelephoneNumber: "02392 856622",
  emergencyContact2FullName: "Neil Hamilton",
  emergencyContact2TelephoneNumber: "04392 856626",
  emergencyContact2AlternativeTelephoneNumber: "04392 856625",
  emergencyContact3FullName: null,
  emergencyContact3TelephoneNumber: null,
  emergencyContact3AlternativeTelephoneNumber: null,
  uses: [
    {
      environment: "MARITIME",
      purpose: "COMMERCIAL",
      activity: "FISHING_VESSEL",
      otherActivityText: "Zorbing",
      moreDetails: "I take people out in my yacht.",
      callSign: "Call me",
      vhfRadio: "true",
      fixedVhfRadio: "true",
      fixedVhfRadioInput: "123456",
      portableVhfRadio: "true",
      portableVhfRadioInput: "123456",
      satelliteTelephone: "true",
      satelliteTelephoneInput: "123456",
      mobileTelephone: "true",
      mobileTelephoneInput1: "0123456789",
      mobileTelephoneInput2: "01234567890",
      otherCommunication: "true",
      otherCommunicationInput: "By fax",
      maxCapacity: "10",
      vesselName: "SS Great Britain",
      portLetterNumber: "1",
      homeport: "England",
      areaOfOperation: "Bristol",
      beaconLocation: "Carry bag",
      imoNumber: "1",
      ssrNumber: "2",
      rssNumber: "3",
      officialNumber: "4",
      rigPlatformLocation: "5",
      aircraftManufacturer: "Boeing",
      principalAirport: "Bristol",
      secondaryAirport: "Cardiff",
      registrationMark: "High flying",
      hexAddress: "Aircraft hex",
      cnOrMsnNumber: "1",
      dongle: "false",
      beaconPosition: "In my carry bag",
      workingRemotelyLocation: "Bristol",
      workingRemotelyPeopleCount: "1",
      windfarmLocation: "Scotland",
      windfarmPeopleCount: "100",
      otherActivityLocation: "Manchester",
      otherActivityPeopleCount: "10",
      additionalBeaconUse: "false",
      climbingMountaineering: "false",
      cycling: "false",
      driving: "false",
      skiing: "false",
      walkingHiking: "false",
      windfarm: "false",
      workingRemotely: "false",
    },
  ],
};
