spring:
  profiles:
    active: default,migration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/beacons}
    username: ${SPRING_DATASOURCE_USER:beacons_service}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  data:
    rest:
      basePath: spring-api
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchReactiveHealthContributorAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  cloud:
    azure:
      active-directory:
        enabled: true
        app-id-uri: ${AZURE_AD_API_ID_URI:api://5cdcbb41-958a-43b6-baa1-bbafd80b4f70}
        credential:
          client-id: ${AZURE_AD_API_CLIENT_ID:5cdcbb41-958a-43b6-baa1-bbafd80b4f70}

server:
  compression:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
      base-path: /spring-api/actuator

beacons:
  openapi:
    github:
      url: https://github.com/mcagov/beacons-service
  scheduled:
    legacy-beacon-search-view: ${BEACONS_SEARCH_VIEW_SCHEDULER_TIMEOUT:30000}
  cors:
    allowedOrigins: ${BEACONS_CORS_ALLOWED_ORIGINS:*}

opensearch:
  source:
    host: ${OPENSEARCH_ENDPOINT:localhost}
    port: 443
    https: true
  credentials:
    enabled: true
    user: ${OPENSEARCH_USER:beacon_service}
    password: ${OPENSEARCH_PASSWORD:password}

export:
  directory: /var/export

backup:
  directory: /var/backup

microsoft-graph:
  client-id: ${MICROSOFT_GRAPH_CLIENT_ID:default}
  client-secret: ${MICROSOFT_GRAPH_CLIENT_SECRET:default}
  b2c-tenant-id: ${MICROSOFT_GRAPH_B2C_TENANT_ID:default}
  b2c-tenant-name: ${MICROSOFT_GRAPH_B2C_TENANT_NAME:TESTB2CMCGA}
