export enum BeaconDeletionReasons {
  SOLD = "SOLD",
  DESTROYED = "DESTROYED",
  REPLACED = "REPLACED",
  INCORRECTLY_REGISTERED = "INCORRECTLY_REGISTERED",
  DUPLICATE = "DUPLICATE",
  OTHER = "OTHER",
}
