import { Environment } from "../lib/registration/types";
import { IEntityLink } from "./entityLink";

export interface IUse {
  id: string;
  environment: Environment;
  purpose?: string;
  activity: string;
  otherActivity?: string;
  callSign?: string;
  vhfRadio?: boolean;
  fixedVhfRadio?: boolean;
  fixedVhfRadioValue?: string;
  portableVhfRadio?: boolean;
  portableVhfRadioValue?: string;
  satelliteTelephone?: boolean;
  satelliteTelephoneValue?: string;
  mobileTelephone?: boolean;
  mobileTelephone1?: string;
  mobileTelephone2?: string;
  otherCommunication?: boolean;
  otherCommunicationValue?: string;
  maxCapacity?: number;
  vesselName?: string;
  portLetterNumber?: string;
  homeport?: string;
  areaOfOperation?: string;
  beaconLocation?: string;
  imoNumber?: string;
  ssrNumber?: string;
  rssNumber?: string;
  officialNumber?: string;
  rigPlatformLocation?: string;
  aircraftManufacturer?: string;
  principalAirport?: string;
  secondaryAirport?: string;
  registrationMark?: string;
  hexAddress?: string;
  cnOrMsnNumber?: string;
  dongle?: boolean;
  beaconPosition?: string;
  workingRemotelyLocation?: string;
  workingRemotelyPeopleCount?: number;
  windfarmLocation?: string;
  windfarmPeopleCount?: string;
  otherActivityLocation?: string;
  otherActivityPeopleCount?: string;
  moreDetails: string;
  mainUse: boolean;
  entityLinks: IEntityLink[];
}
