export const BEACON_TYPES = [
  "ELT",
  "ELT (Auto Portable)",
  "ELT (Auto)",
  "ELT (Auto) / PLB",
  "ELT (Automatic Deployable)",
  "ELT (Automatic Fixed)",
  "ELT (Man)",
  "ELT (Man) - Survival",
  "ELT (S)",
  "ELT (Auto) / ELT (Portable)",
  "ELT (Auto) / ELT (Portable) / ELT (Survival) / PLB",
  "ELT (Automatic Fixed) and ELT (Automatic Portable)",
  "ELT (Man) / PLB",
  "ELT (S) / PLB",
  "ELT, SGB, Second Generation",
  "EPIRB",
  "EPIRB FF (S-VDR)",
  "EPIRB FF (VDR)",
  "EPIRB, SGB, Second Generation",
  "FF / Non FF EPIRB",
  "FF EPIRB",
  "Non FF EPIRB",
  "Non FF EPIRB / ELT (Man) / PLB",
  "PLB",
  "PLB / Non FF EPIRB",
  "PLB, SGB, Second Generation",
  "SSAS",
];
