export enum Pages {
  summary = "",
  beaconDetails = "details",
  beaconInformation = "beacon-information",
  aboutBeaconOwner = "about-beacon-owner",
  beaconOwnerAddress = "beacon-owner-address",
  emergencyContact = "emergency-contact",
  complete = "complete",
  environment = "environment",
  purpose = "purpose",
  activity = "activity",
  aboutTheVessel = "about-the-vessel",
  vesselCommunications = "vessel-communications",
  aboutTheAircraft = "about-the-aircraft",
  aircraftCommunications = "aircraft-communications",
  landCommunications = "land-communications",
  moreDetails = "more-details",
}
