version: "3.8"

services:
  webapp:
    build:
      context: .
      target: nextjs-app
    ports:
      - "3000:3000"
    environment:
#      AAD_API_ID: $AAD_API_ID
#      AAD_TENANT_ID: $AAD_API_ID
#      API_URL: $API_URL
#      BASIC_AUTH: $BASIC_AUTH
#      GOV_NOTIFY_API_KEY: $GOV_NOTIFY_API_KEY
#      GOV_NOTIFY_FEEDBACK_EMAIL_ADDRESS: $GOV_NOTIFY_FEEDBACK_EMAIL_ADDRESS
#      NEXTAUTH_URL: $NEXTAUTH_URL
      REDIS_URI: redis://redis:6379
#      WEBAPP_CLIENT_ID: $WEBAPP_CLIENT_ID
#      WEBAPP_CLIENT_SECRET: $WEBAPP_CLIENT_SECRET
    env_file:
      - .env.local

  redis:
    image: redis:6
    ports:
      - "6379:6379"
