name: Publish Service image

on:
  workflow_call:
    inputs:
      tag:
        description: The tag to add to the published Docker image, e.g. "v1.0.1"
        required: true
        type: string
      registry_url:
        description: The URL of the registry where the image should be published
        required: true
        type: string
      repository_name:
        description: The name of the image to be published
        required: false
        default: beacons-service
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

defaults:
  run:
    working-directory: service

jobs:
  docker_build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry_url }}
          username: ${{ secrets.aws_access_key_id }}
          password: ${{ secrets.aws_secret_access_key }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: service
          push: true
          tags: ${{ inputs.registry_url }}/${{ inputs.repository_name }}:${{ inputs.tag }}
