name: Destroy Performance

env:
  TERRAFORM_VERSION: 1.0.0

jobs:
  terraform_destroy_performance:
    if: github.ref == 'refs/heads/main' && always()
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment: performance
    defaults:
      run:
        working-directory: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_WORKSPACE: performance
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: main
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
